project_id = "aqyrveunmqufurmeikqn"

[functions.generate-scenario]
verify_jwt = false

[functions.cors]
allowed_origins = ["*"]
allowed_headers = ["authorization", "x-client-info", "apikey", "content-type"]
allowed_methods = ["POST", "OPTIONS"]
