// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqyrveunmqufurmeikqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxeXJ2ZXVubXF1ZnVybWVpa3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNTg4ODAsImV4cCI6MjA3MDYzNDg4MH0.-Dwyv0cGqD5QGt0I4d2K7XiCp5TL4QsxcbP7eiuHjVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});